In [15]:
import numpy as np
import gym
import random

In [16]:
# Creating the Environment

env = gym.make('FrozenLake-v0')

In [17]:
# Creating the Q Table and set it to 0

action_size = env.action_space.n
state_size = env.observation_space.n

In [18]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
# Specifying HyperParameters 

total_episodes = 15000
learning_rate = 0.8
max_steps = 99
gamma = 0.95

# Exploration Paramaters

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [20]:
# Using Q-Learning algorithm

rewards = []

for episode in range(total_episodes):
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0
  for step in range(max_steps):
    exp_exp_tradeoff = random.uniform(0,1)
    if exp_exp_tradeoff > epsilon: # Do Exploitation(return the max value of Q-Table)
      action = np.argmax(qtable[state,:])
    else:
      action = env.action_space.sample()
    new_state, reward, done, info = env.step(action)
    # Update the Q-Table after performing the action
    qtable[state,action] = qtable[state,action] + learning_rate*(reward + gamma*np.max(qtable[new_state,:]) - qtable[state,action])
    total_rewards += reward
    state = new_state

    if done == True:
      break;  # End of Episode
  # Reduce epsilon as we aldready know some part of the environment due to the exploration
  epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
  rewards.append(total_rewards)

print('score over time ' + str(sum(rewards)/total_episodes))
print(qtable)


    



score over time 0.4703333333333333
[[1.76177301e-01 6.27906775e-02 5.91417972e-02 3.02900208e-02]
 [9.18574741e-03 1.12605406e-02 3.07160728e-03 2.48896598e-01]
 [1.22577726e-02 1.64618421e-02 5.03164666e-03 1.31941526e-02]
 [1.24052656e-04 9.72868609e-04 5.31341266e-03 5.89078803e-02]
 [1.13109854e-01 4.59728321e-02 5.21029457e-03 3.09910041e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.89907346e-04 8.90664718e-02 4.37536255e-04 7.61929233e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.44019621e-02 3.19120475e-02 3.71351602e-02 8.90098116e-02]
 [4.55541541e-02 1.42241939e-01 3.71196766e-03 1.33870646e-02]
 [6.48439636e-01 1.77995676e-03 2.22200580e-03 1.13172775e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.94880183e-02 1.20869027e-01 7.62731619e-01 1.28183922e-01]
 [3.90864298e-02 7.28525458e-02 6.03442765e-02 9.93103660e-01]
 [0.00000000e+00 0.0

In [31]:
env.reset()

for episode in range(10):
  state = env.reset()
  step = 0
  done = False
  print('EPISODE ', episode)
  for step in range(max_steps):
    action = np.argmax(qtable[state,:])
    new_state, reward , done , info = env.step(action)
    if done:
      env.render()
      print('Number of steps ',step)
      break
    state = new_state
env.close()

EPISODE  0
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  85
EPISODE  1
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  21
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps  63
EPISODE  3
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  27
EPISODE  4
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  57
EPISODE  5
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  73
EPISODE  6
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  22
EPISODE  7
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  36
EPISODE  8
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps  34
EPISODE  9
